apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: goexpert
  labels:
    app: server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: aleroxac/goexpert-k8s:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "25m"
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: server-svc
  namespace: goexpert
  labels:
    app: server
spec:
  type: NodePort
  selector:
    app: server
  ports:
  - port: 80
    targetPort: 8080
